// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlhoJdnMEdlzyUIlrkm60vCuFgBTu7yEc',
    appId: '1:481426157711:web:269f1a22765d6f510dc0fa',
    messagingSenderId: '481426157711',
    projectId: 'care-connect-flutter',
    authDomain: 'care-connect-flutter.firebaseapp.com',
    storageBucket: 'care-connect-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh0acpRe5ZUanNEssNOCHcDpwoCLO5K5w',
    appId: '1:481426157711:android:7dbc1b1412a593360dc0fa',
    messagingSenderId: '481426157711',
    projectId: 'care-connect-flutter',
    storageBucket: 'care-connect-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLaf5A5S8ujGh3nX37UQ2gPY5TmPrzZE',
    appId: '1:481426157711:ios:26fb68ff8bb370a30dc0fa',
    messagingSenderId: '481426157711',
    projectId: 'care-connect-flutter',
    storageBucket: 'care-connect-flutter.appspot.com',
    iosBundleId: 'com.example.careConnect',
  );
}
